### ISSUE TITLE
Issue with Maven-war-plugin 2.6 version

### ISSUE THREAD

**Issue by navakrishna** [redfish4ktc/maven-soapui-extension-plugin#140]
Hello,

    I am implementing npm and gulp integration with maven. I am excluding node_modules which are generated from npm and other functionality related js files in maven-war-plugin of  pom.xml  . In maven war plugin version 2.6 these files are added to war. So, I have degraded the version war version to 2.3 then it worked. Can some one suggest, what might be the issue and is this issue fixed in next version.

Regards,
Nava

**Comment by redfish4ktc** [comment]
@navakrishna are you sure you are posting the issue in the right repository?
I don't understand why your issue is related to the soapui plugin

**Comment by navakrishna** [comment]
Hello Sorry, I have posted under wrong group. This issue is not related to soap UI plugin.

**Comment by redfish4ktc** [comment]
ok, so closing this issue
