### ISSUE TITLE
multiple testcase based on custom property

### ISSUE THREAD

**Issue by tremkonzah** [redfish4ktc/maven-soapui-extension-plugin#142]
Hello

how to use this plugin to run multiple testcase based on custom property?
e.g
Case 1 - custom property Hello=Y
Case 2 - custom property Hello=N
Case 3 - custom property Hello=N
Case 4 - custom property Hello=Y

i want to all testcase -DHello=Y

**Comment by redfish4ktc** [comment]
Hello
I am not sure to understand your question. Is that possible from the command line? if not, it may not possible out of the box

**Comment by redfish4ktc** [comment]
Closing as there is not activity on this issue.
Please free to reopen it if you need more information.
