### ISSUE TITLE
java.lang.NoClassDefFoundError: com/eviware/soapui/tools/AbstractSoapUIRunner

### ISSUE THREAD

**Issue by linjin-harvey** [redfish4ktc/maven-soapui-extension-plugin#143]
Below is my pom.xml:
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>BO-Automation</groupId>
    <artifactId>webconnect</artifactId>
    <version>1.0-SNAPSHOT</version>
    <name>Maven 2 SoapUI Sample</name>
    <url>http://maven.apache.org</url>

    <properties>

    </properties>

    <pluginRepositories>
        <pluginRepository>
            <id>SmartBearPluginRepository</id>
            <url>http://www.soapui.org/repository/maven2/</url>
        </pluginRepository>
        <pluginRepository>
            <id>eviwarePluginRepository</id>
            <url>http://www.eviware.com/repository/maven2/</url>
        </pluginRepository>
    </pluginRepositories>

    <repositories>
        <repository>
            <id>SmartBearPluginRepository</id>
            <url>http://www.soapui.org/repository/maven2/</url>
        </repository>
        <repository>
            <id>eviwarePluginRepository</id>
            <url>http://www.eviware.com/repository/maven2/</url>
        </repository>
    </repositories>

    <build>

            <plugins>
                <plugin>
                    <groupId>com.github.redfish4ktc.soapui</groupId>
                    <artifactId>maven-soapui-extension-plugin</artifactId>
                    <version>4.6.4.2</version>
                    <dependencies>
                        <dependency>
                            <groupId>com.smartbear.soapui</groupId>
                            <artifactId>soapui-pro-maven-plugin</artifactId>
                            <version>4.6.4</version>
                        </dependency>
                        <dependency>
                            <groupId>com.smartbear.soapui</groupId>
                            <artifactId>soapui-pro</artifactId>
                            <version>4.6.4</version>
                        </dependency>
                    </dependencies>

                    <executions>
                        <execution>
                            <id>soapUI1</id>
                            <phase>test</phase>
                            <goals>
                                <goal>test</goal>
                            </goals>
                            <configuration>
                                <runnerType>OSS</runnerType>
                                <projectFile>${basedir}\src\test\resources\soapuiProjects\user-authentication-soapui-project.xml</projectFile>
                                <outputFolder>${basedir}/build/soapui-reports/</outputFolder>
                                <exportAll>true</exportAll>
                                <junitHtmlReport>false</junitHtmlReport>
                                <junitReport>true</junitReport>
                                <testFailIgnore>true</testFailIgnore>
                            </configuration>

                        </execution>
                    </executions>
                </plugin>

            </plugins>

    </build>

</project>

I can run the 'mvn test' in my local success. However when i execute the command on Jenkins server, it always filed with below message: 

[INFO] --- maven-soapui-extension-plugin:4.6.4.2:test (soapUI1) @ webconnect ---
[WARNING] Error injecting: org.ktc.soapui.maven.extension.TestMojo
java.lang.NoClassDefFoundError: com/eviware/soapui/tools/AbstractSoapUIRunner
	at java.lang.Class.getDeclaredConstructors0(Native Method)
	at java.lang.Class.privateGetDeclaredConstructors(Class.java:2663)
	at java.lang.Class.getDeclaredConstructors(Class.java:2012)
	at com.google.inject.spi.InjectionPoint.forConstructorOf(InjectionPoint.java:245)
	at com.google.inject.internal.ConstructorBindingImpl.create(ConstructorBindingImpl.java:99)
	at com.google.inject.internal.InjectorImpl.createUninitializedBinding(InjectorImpl.java:657)
	at com.google.inject.internal.InjectorImpl.createJustInTimeBinding(InjectorImpl.java:875)
	at com.google.inject.internal.InjectorImpl.createJustInTimeBindingRecursive(InjectorImpl.java:798)
	at com.google.inject.internal.InjectorImpl.getJustInTimeBinding(InjectorImpl.java:281)
	at com.google.inject.internal.InjectorImpl.getBindingOrThrow(InjectorImpl.java:213)
	at com.google.inject.internal.InjectorImpl.getProviderOrThrow(InjectorImpl.java:998)

I checked the Jenkins server, found the jar is not been downloaded on jenkins server.

**Comment by redfish4ktc** [comment]
Strange, can you run the command on Jenkins with the -e option and provide the full stack trace?

**Comment by redfish4ktc** [comment]
Closing as there is not activity on this issue.
Please free to reopen it if you need more information.
