### ISSUE TITLE
Property Transfer in JSON format

### ISSUE THREAD

**Issue by sivaprakash567** [redfish4ktc/maven-soapui-extension-plugin#145]
Hi,
I am using 'maven-soapui-extension-plugin' version - 4.6.4.2 to generate the customized Junit report.
Report is getting generated fine but having an issue while transferring the property in JSON format as attached below.

![image](https://user-images.githubusercontent.com/29778573/27692163-a2140f50-5d03-11e7-871c-94adea2d2589.png)

But the Property transfer step is getting failed and giving below exception.

The same property transfer works fine when I use 'soapui-pro-maven-plugin' version -5.1.2.
I want to use 'maven-soapui-extension-plugin' because I need to customize the Junit reports.

It is little urgent, Please advice. 

Error:com.eviware.soapui.impl.wsdl.teststeps.PropertyTransferException: error: Unexpected element: CDATA

----------------- Messages ------------------------------
Error performing transfer [GetDays] - error: Unexpected element: CDATA
----------------------------------------------------
GetDays transferred [[error: Unexpected element: CDATA]] from [/closedEnquiry.Response] to [/dormant.noOfDays]
------------ source path -------------
atomLinks.lstLinkReferences[0].link.response.totalResults

**Comment by redfish4ktc** [comment]
Hello
I guess the issue comes from the Soapui Pro version used by the plugin: 4.6.4
Something you can try is to force the 'maven-soapui-extension-plugin' to use a newest version by doing the following:

```xml
<plugin>
  <groupId>com.github.redfish4ktc.soapui</groupId>
  <artifactId>maven-soapui-extension-plugin</artifactId>
  <version>4.6.4.2</version>
  <dependencies>
    <dependency>
      <groupId>com.smartbear.soapui</groupId>
      <artifactId>soapui-pro</artifactId>
      <version>5.1.2</version>
    </dependency>
    <dependency>
      <groupId>com.smartbear.soapui</groupId>
      <artifactId>soapui</artifactId>
      <version>5.1.2</version>
    </dependency>
  </dependencies>
</plugin>
```
It may produce side effects but you can give it a try

**Comment by sivaprakash567** [comment]
Thanks, It worked fine. :)

**Comment by redfish4ktc** [comment]
Ok perfect, so I close the issue
